# Generated by Django 2.2 on 2021-04-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='customer_id',
            field=models.IntegerField(null=True),
        ),
    ]
