# Generated by Django 2.2 on 2021-04-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210411_1159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalFees',
        ),
        migrations.DeleteModel(
            name='ProductMedia',
        ),
        migrations.DeleteModel(
            name='ProductVarians',
        ),
        migrations.DeleteModel(
            name='SubtractionFees',
        ),
        migrations.AddField(
            model_name='orders',
            name='additional_fee',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='media',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='varian',
            field=models.TextField(default='[]', null=True),
        ),
    ]
