# Generated by Django 2.2 on 2021-04-21 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210421_0227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Carts',
        ),
        migrations.AlterModelTable(
            name='carts',
            table='carts',
        ),
    ]
