# Generated by Django 2.2 on 2021-04-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210421_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengiriman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('startRange', models.FloatField(default=0)),
                ('endRange', models.FloatField(default=10000)),
            ],
            options={
                'db_table': 'pengiriman',
            },
        ),
        migrations.RemoveField(
            model_name='orders',
            name='is_pay',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.CharField(default='menunggu pembayaran', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_status_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_data',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(choices=[('checkout', 'checkout'), ('fail', 'fail'), ('success', 'success')], default='checkout', max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='shipment_data',
            field=models.TextField(null=True),
        ),
    ]
