# Generated by Django 2.2 on 2021-04-21 04:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210421_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='invoice',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
