# Generated by Django 2.2 on 2021-04-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_orders_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='kabupaten_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='provinsi_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
